### ISSUE TITLE
Desktop App Crash: Cannot round NaN value.

### ISSUE THREAD

**Issue by Shabinder** [mahozad/wavy-slider#16]
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Cannot round NaN value.
at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1165)
at ir.mahozad.multiplatform.wavyslider.material3.WavySliderKt$WavySliderImpl$2$1.measure-3p2s80s(WavySlider.kt:602)
at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
at androidx.compose.foundation.layout.SizeNode.measure-3p2s80s(Size.kt:838)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
at androidx.compose.material3.MinimumInteractiveModifierNode.measure-3p2s80s(InteractiveComponentSize.kt:84)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(Size.kt:699)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
```

<img width="1507" alt="image" src="https://github.com/mahozad/wavy-slider/assets/44765050/10144347-ace1-4007-a1c0-ae6af274f748">

**Comment by Shabinder** [comment]
Fixed, my bad
